#!/usr/bin/env python3

# 18.py
#
# python-training/www.practicepython.org (c) 2017 by Franco Masotti
#                                        <franco.masotti@student.unife.it>
#
# python-training/www.practicepython.org is licensed under a
# Creative Commons Attribution 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by/4.0/>.

# Create a program that will play the “cows and bulls” game with the user. The 
# game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
# For every digit that the user guessed correctly in the correct place, they 
# have a “cow”. For every digit the user guessed correctly in the wrong place 
# is a “bull.” Every time the user makes a guess, tell them how many “cows” and 
# “bulls” they have. Once the user guesses the correct number, the game is 
# over. 
# Keep track of the number of guesses the user makes throughout teh game and 
# tell the user at the end.
# Say the number generated by the computer is 1038. An example interaction 
# could look like this:
#
# Welcome to the Cows and Bulls Game! 
# Enter a number: 
#  >>> 1234
#  2 cows, 0 bulls
#  >>> 1256
#  1 cow, 1 bull
#  ...
#
# Until the user guesses the number.

# In this version duplicate digits are possible.
# You can modify the number of digits to make thing more difficult.

import random

DIGITS = 4

MIN = 10**(DIGITS-1)
MAX = (10**DIGITS)-1

# Between 10^(DIGITS-1) and (10^DIGITS) -1
def gen_number():
    return random.randint(MIN,MAX)

def status(cgnumber, number):
    cows = 0
    bulls = 0
    sn = str(number)
    sc = str(cgnumber)
    i = 0
    j = 0

    # Very naive approach but for 4 digits per number
    # it's feasable
    for cn in sc:
        j = 0
        for en in sn:
            if en == cn:
                if i == j:
                    cows += 1
                else:
                    bulls += 1
            j+=1
        i+=1

    return [cows, bulls]

def main_loop(cgnumber):
    guesses = 0
    found = False
    cows = 0
    bulls = 0
    print (cgnumber)

    while cows != DIGITS:
        guesses += 1
        number = 0
        while number < MIN or number > MAX:
            number = int(input("Enter a number between " + str(MIN) + " and " + str(MAX) + ": "))
        cows, bulls = status(cgnumber,number)
        print (str(cows) + " cows, " + str(bulls) + " bulls.")

    return guesses

# The real main method.
if __name__ == "__main__":

    print("Welcome to the Cows and Bulls Game!")
    guesses = main_loop(gen_number())
    print ("You've made " + str(guesses) + " guesses")
